[package]
name = "RazorLibs"
version = "1.0.0"
authors = []

[addresses]
std = "0x1"
razor_libs = "_"
alice = "0xa11ce"
bob = "0xb0b"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dev-dependencies]
